name: gtfs_tools

channels:
  - esri
  - conda-forge

dependencies:
  - arcgis
  - black>=21
  - h3-py
  - jupyterlab
  - jupyterlab_code_formatter
  - nodejs
  - pip
  - pytest
  - python
  - pyarrow
  - scikit-learn
  - pip:
    - autodocsumm
    - azure-storage-blob
    - build
    - bump2version
    - ipykernel
    - mkdocs
    - mkdocs-glightbox
    - mkdocs-include-markdown-plugin
    - mkdocs-jupyter
    - mkdocs-material
    - mkdocstrings[python]>=0.18
    - placekey
    - twine
