site_name: GTFS-Tools 0.2.0

docs_dir: mkdocs
site_dir: ../docs

nav:
  - Home: index.md
  - GTFS Overview: gtfs.md
  - API: api.md

theme:
  name: material

  features:
    - content.code.copy
    - content.code.select

  palette:

    # Palette toggle for automatic mode
    - media: "(prefers-color-scheme)"
      primary: blue
      accent: green
      toggle:
        icon: material/brightness-auto
        name: Switch to light mode

    # Palette toggle for light mode
    - media: "(prefers-color-scheme: light)"
      scheme: default
      primary: blue
      accent: green
      toggle:
        icon: material/brightness-7
        name: Switch to dark mode

    # Palette toggle for dark mode
    - media: "(prefers-color-scheme: dark)"
      scheme: slate
      primary: blue
      accent: green
      toggle:
        icon: material/brightness-4
        name: Switch to system preference

markdown_extensions:
  - pymdownx.highlight:
      anchor_linenums: true
      line_spans: __span
      pygments_lang_class: true
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - pymdownx.superfences

plugins:

# enable lightbox, enlarging images
- glightbox

# enable embedding csv files
- include-markdown

# extension converting included notebooks into html at build time
- mkdocs-jupyter:
    include_source: True

# extension handling pulling docstrings from Python package
- mkdocstrings:

    # explicitly enable generation of objects.ini facilitating intersphinx mapping
    enable_inventory: true

    # show_root_heading: false

    handlers:
      python:

        # where to find the local package
        paths: [../src]

        # referenced python objects will be linked
        inventories:
        - https://docs.python.org/3/objects.inv

        # use Google docstrings style
        options:
          docstring_style: google
